name = "CIJ"
uuid = "94ef64d9-0af0-5988-adf1-f968d20ebcf5"
authors = ["Andy Nowacki <a.nowacki@leeds.ac.uk>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
CIJMakieExt = ["GeometryBasics", "Makie"]

[compat]
GeometryBasics = "0.4, 0.5"
Makie = "0.23, 0.24"
Rotations = "1"
StaticArrays = "0.12, 1"
julia = "1.6"

[extras]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
